### PR TITLE
Add the GitHub ribbon.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by jpeach** [comment]
@ryandesign Is this right?

**Comment by ryandesign** [comment]
Yes, but using the GitHub ribbon will make it impossible to use the navigation menu that Bootstrap shows when the window is narrow.

**Comment by jpeach** [comment]
Yeh the ribbon makes the nav menu unusable :(

**Comment by jpeach** [comment]
It's been 7 years without me coming up with anything better, so I'm just going to merge this 😂

**Pull request merged**
